COMMENT = enhanced motif window manager (MWM fork)

V = 1.1
DISTNAME = emwm-v${V}
PKGNAME = emwm-${V}

CATEGORIES = x11

HOMEPAGE = https://fastestcode.org/emwm.html

MAINTAINER = izzy Meyer <izder456@disroot.org>

# LGPL v2.1
PERMIT_PACKAGE = Yes

GH_ACCOUNT = alx210
GH_PROJECT = emwm
GH_TAGNAME = v${V}

COMPILER =		base-clang ports-gcc

LIB_DEPENDS = x11/motif

NO_TEST =		Yes

.include <bsd.port.mk>