COMMENT = session manager and a toolchest-like application launcher.

V = 1.1
DISTNAME = emwm-utils-v${V}
PKGNAME = xmsm-${V}
CATEGORIES = x11

HOMEPAGE = https://fastestcode.org/emwm.html

MAINTAINER = izzy Meyer <izder456@disroot.org>

# MIT
PERMIT_PACKAGE = Yes

GH_ACCOUNT = alx210
GH_PROJECT = emwm-utils
GH_TAGNAME = v${V}

COMPILER =		base-clang ports-gcc

LIB_DEPENDS = x11/motif

NO_TEST =		Yes

.include <bsd.port.mk>