COMMENT =		cat that chases around your cursor

V =			1.2
PKGNAME =		oneko-sakura-$V

CATEGORIES =		games

HOMEPAGE =		http://www.daidouji.com/oneko

# License: Custom, includes derivates of CARDCAPTOR SAKURA, see https://www.clamp-net.com
PERMIT_PACKAGE =	Yes

WANTLIB +=		X11 Xau Xdmcp Xext c m

SITES =			http://www.daidouji.com/oneko/distfiles/

DISTNAME =		oneko-$V.sakura.5

COMPILER =		base-clang ports-gcc base-gcc

CONFIGURE_STYLE =	imake

.include <bsd.port.mk>
