COMMENT =		cat that chases around your cursor

V =			1.2
PKGNAME =		oneko
FULLPKGNAME =		oneko-sakura-$V

CATEGORIES =		games

HOMEPAGE =		http://www.daidouji.com/oneko

PERMIT_PACKAGE =	Yes

WANTLIB += 		X11 Xau Xdmcp Xext c m

SITES =			http://www.daidouji.com/oneko/distfiles/

DISTNAME =		${PKGNAME}-$V.sakura.5

COMPILER =		base-clang ports-gcc base-gcc

CONFIGURE_STYLE =	imake

.include <bsd.port.mk>
